on: push
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno task build
      - run: deno task test

# Copy the relevant libs into the deployment directory. This will not be
# necessary once https://ufork.org is live.

      - run: mkdir -p apps/debugger/ufork.org/wasm
      - run: cp -R lib apps/debugger/ufork.org/lib
      - run: cp -R vm/js apps/debugger/ufork.org/js
      - run: cp vm/wasm/*.wasm apps/debugger/ufork.org/wasm/
      - run: 'sed -e "s,<!-- importmap goes here -->,<script type=\"importmap\">{\"imports\": {\"https://ufork.org/\": \"/uFork/ufork.org/\"}}</script>,g" -i apps/debugger/index.html'
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'apps/debugger/'
      - uses: actions/deploy-pages@v2
